using ConsoleApp;
Assistant assistant = new Assistant("Mike", "Aivazovsky");
assistant.GetFullInformation();
Console.WriteLine("Next position:");
Console.WriteLine(assistant.Promotion());
Console.WriteLine("New position:");
Console.WriteLine(assistant.Promote());
Console.WriteLine();
Performer performer = assistant.Promote();
performer.GetFullInformation();
Console.WriteLine("Next position:");
Console.WriteLine(performer.Promotion());
Console.WriteLine("New position:");
Console.WriteLine(performer.Promote());
Console.WriteLine();
Manager manager = performer.Promote();
manager.GetFullInformation();
Console.WriteLine("Next position:");
Console.WriteLine(manager.Promotion());
Console.WriteLine("New position:");
Console.WriteLine(manager.Promote());
Console.WriteLine();
Boss boss = manager.Promote();
boss.GetFullInformation();
Console.WriteLine("Next position:");
Console.WriteLine(boss.Promotion());
Console.WriteLine("New position:");
Console.WriteLine(boss.Promote());
